name: todo_tuto
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_slidable: ^4.0.0
  
  hydrated_bloc: ^10.0.0
  path_provider: ^2.0.15
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  meta: ^1.15.0
  bloc: ^9.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

 
